### PR TITLE
M13 support. 1.3.0 version

### LINKED ISSUE #3: M13 support

### PR DESCRIPTION
**Pull request by dsvoronin**
fixes #3

### CODE REVIEW

**Comment by SalomonBrys** [comment]
Great work, thanks :+1: :smile:

**Comment by SalomonBrys** [comment]
Released to maven central

**Comment by dsvoronin** [comment]
@SalomonBrys forgot to update Readme

**Comment by SalomonBrys** [comment]
On the way ;)

**Pull request merged**
